//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPS.Areas.Document.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOPS.Areas.Document.Resources.EmployeeReport", typeof(EmployeeReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba komentarzy.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pracowników.
        /// </summary>
        public static string EmploteeCount {
            get {
                return ResourceManager.GetString("EmploteeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana w ciągu roku.
        /// </summary>
        public static string EmployeeCountYearChange {
            get {
                return ResourceManager.GetString("EmployeeCountYearChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba produktów w obiegu.
        /// </summary>
        public static string ExistingProductCount {
            get {
                return ResourceManager.GetString("ExistingProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączy koszt produktów.
        /// </summary>
        public static string ExistingProductSumPrice {
            get {
                return ResourceManager.GetString("ExistingProductSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia cena produktów.
        /// </summary>
        public static string ProductAveragePrice {
            get {
                return ResourceManager.GetString("ProductAveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia ocena produktów.
        /// </summary>
        public static string ProductAverageRating {
            get {
                return ResourceManager.GetString("ProductAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najlepiej oceniony.
        /// </summary>
        public static string ProductBestRated {
            get {
                return ResourceManager.GetString("ProductBestRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całkowita liczba produktów.
        /// </summary>
        public static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęściej komentowany.
        /// </summary>
        public static string ProductMostCommented {
            get {
                return ResourceManager.GetString("ProductMostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba ocen.
        /// </summary>
        public static string RatingCount {
            get {
                return ResourceManager.GetString("RatingCount", resourceCulture);
            }
        }
    }
}
