//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPS.Areas.Document.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Product {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOPS.Areas.Document.Resources.Product", typeof(Product).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string CompanyAddressStreet {
            get {
                return ResourceManager.GetString("CompanyAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        public static string CompanyAddressZipCode {
            get {
                return ResourceManager.GetString("CompanyAddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CompanyCity {
            get {
                return ResourceManager.GetString("CompanyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer data.
        /// </summary>
        public static string CompanyData {
            get {
                return ResourceManager.GetString("CompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string CompanyNIP {
            get {
                return ResourceManager.GetString("CompanyNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON.
        /// </summary>
        public static string CompanyREGON {
            get {
                return ResourceManager.GetString("CompanyREGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba komentarzy.
        /// </summary>
        public static string eCommentCount {
            get {
                return ResourceManager.GetString("eCommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pracowników.
        /// </summary>
        public static string eEmploteeCount {
            get {
                return ResourceManager.GetString("eEmploteeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana w ciągu roku.
        /// </summary>
        public static string eEmployeeCountYearChange {
            get {
                return ResourceManager.GetString("eEmployeeCountYearChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba produktów w obiegu.
        /// </summary>
        public static string eExistingProductCount {
            get {
                return ResourceManager.GetString("eExistingProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączy koszt produktów.
        /// </summary>
        public static string eExistingProductSumPrice {
            get {
                return ResourceManager.GetString("eExistingProductSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia cena produktów.
        /// </summary>
        public static string eProductAveragePrice {
            get {
                return ResourceManager.GetString("eProductAveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia ocena produktów.
        /// </summary>
        public static string eProductAverageRating {
            get {
                return ResourceManager.GetString("eProductAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najlepiej oceniony.
        /// </summary>
        public static string eProductBestRated {
            get {
                return ResourceManager.GetString("eProductBestRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całkowita liczba produktów.
        /// </summary>
        public static string eProductCount {
            get {
                return ResourceManager.GetString("eProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęściej komentowany.
        /// </summary>
        public static string eProductMostCommented {
            get {
                return ResourceManager.GetString("eProductMostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba ocen.
        /// </summary>
        public static string eRatingCount {
            get {
                return ResourceManager.GetString("eRatingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing product identifier.
        /// </summary>
        public static string ExistingProductId {
            get {
                return ResourceManager.GetString("ExistingProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of orgin.
        /// </summary>
        public static string ProductCountryOfOrigin {
            get {
                return ResourceManager.GetString("ProductCountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string ProductExpirationDate {
            get {
                return ResourceManager.GetString("ProductExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product identifier.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        public static string QRContent {
            get {
                return ResourceManager.GetString("QRContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested price.
        /// </summary>
        public static string SuggestedPrice {
            get {
                return ResourceManager.GetString("SuggestedPrice", resourceCulture);
            }
        }
    }
}
