// <auto-generated />
namespace SOPS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mi12124 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mi12124));
        
        string IMigrationMetadata.Id
        {
            get { return "201812221958271_mi12124"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
